name: image_provider
description: A new Flutter package project.
version: 0.4.0

publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  camera: ^0.10.1
  native_device_orientation: ^1.1.4
  flutter_image_compress: ^1.1.3
  path_provider: ^2.0.11
  multi_image_picker2: ^5.0.2

  #Web
  file_picker: ^5.2.4
  permission_asker:
    git:
      url: "https://github.com/trailon/permission_asker.git"
  focused_image_widget:
    git:
      url: "https://github.com/trailon/focused_image_widget.git"
      ref: d6efdc154b1fa1b5d37e327154bcce0f440a29ae

  dialog_service:
    git:
      url: https://github.com/trailon/dialog_service.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - image_provider_assets/imgs/


