name: image_provider
description: A new Flutter package project.
version: 0.4.0

publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  camera: ^0.10.1
  native_device_orientation: ^1.1.4
  flutter_image_compress: ^1.1.3
  path_provider: ^2.0.11
  permission_asker: ^1.0.0+1
  multi_image_picker2: ^5.0.2

  #Web
  file_picker: ^5.2.4
  focused_image_widget:
    git:
      url: "git@github.com:CosmosExmo/focused_image_widget.git"

  dialog_service:
    git:
      url: https://github.com/CosmosExmo/dialog_service.git
      ref: 4a63d2c5909e78d412fe9cb8237eb072019d2fa1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - image_provider_assets/imgs/


