name: image_provider
description: A new Flutter package project.
version: 0.3.9
homepage: https://github.com/DestechHasarWebsiteleri/image_provider

publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=3.3.8"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.4
  camera: ^0.10.0+4
  native_device_orientation: ^1.1.4

  flutter_image_compress: ^1.1.3
  permission_handler: ^10.2.0
  path_provider: ^2.0.11

  #Web
  file_picker: ^5.2.2

# deprecated
  device_info: ^2.0.3
  multi_image_picker2: ^5.0.2


  dialog_service:
    git:
      url: https://github.com/CosmosExmo/dialog_service.git
      ref: 4a63d2c5909e78d412fe9cb8237eb072019d2fa1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:


